packages:
  all:
    compiler: [xl, gcc, clang]
    providers:
      mpi: [spectrum-mpi]
      blas: [essl]
      lapack: [netlib-lapack]
  essl:
    variants: threads=none
    version: [6.2.1]
    buildable: false
    externals:
    - spec: essl@6.2.1
      prefix: /usr/tcetmp/packages/essl/essl-6.2.1
  veclibfort:
    buildable: false
  intel-parallel-studio:
    buildable: false
  intel-mkl:
    buildable: false
  atlas:
    buildable: false
  openblas:    # OpenBLAS can be built only with gcc
    buildable: false
  libflame:
    buildable: false
  cray-libsci:
    buildable: false
  netlib-lapack:   # prefer netlib-lapack with '+external-blas' and '~lapacke' variant
    variants: +external-blas~lapacke
  mvapich2-gdr:
    buildable: false
    externals:
    - spec: mvapich2-gdr@rolling-release%gcc@7.3.1
      prefix: /usr/tce/packages/mvapich2/mvapich2-2021.05.28-cuda-11.6.1-gcc-7.3.1/
  spectrum-mpi:
    buildable: false
    externals:
    - spec: spectrum-mpi@rolling-release%xl@16.1.1
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-xl-2022.08.19-cuda-11.7.0
    - spec: spectrum-mpi@rolling-release%gcc@4.9.3
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-4.9.3
    - spec: spectrum-mpi@rolling-release%gcc@7.3.1
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-7.3.1
    - spec: spectrum-mpi@rolling-release%gcc@8.3.1
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-gcc-8.3.1
    - spec: spectrum-mpi@rolling-release%clang@11.0.0
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-ibm-11.0.0
    - spec: spectrum-mpi@rolling-release%clang@12.0.1
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-12.0.1
    - spec: spectrum-mpi@rolling-release%clang@13.0.0
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-13.0.0
    - spec: spectrum-mpi@rolling-release%clang@14.0.5
      prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-14.0.5
  cmake:
    buildable: false
    externals:
    - spec: cmake@3.18.0
      prefix: /usr/tce/packages/cmake/cmake-3.18.0
    - spec: cmake@3.23.1
      prefix: /usr/tce/packages/cmake/cmake-3.23.1
  cuda:
    buildable: false
    externals:
    - spec: cuda@11.1.1
      prefix: /usr/tce/packages/cuda/cuda-11.1.1
    - spec: cuda@11.6.1
      prefix: /usr/tce/packages/cuda/cuda-11.6.1
    - spec: cuda@11.6.2
      prefix: /usr/tce/packages/cuda/cuda-11.6.2
    - spec: cuda@11.7.0
      prefix: /usr/tce/packages/cuda/cuda-11.7.0
  rdma-core:
    buildable: false
    externals:
    - spec: rdma-core@system
      prefix: /usr
  libx11:
    version: [system]
    buildable: false
    externals:
    - spec: libx11@system
      prefix: /usr
  libxt:
    version: [system]
    buildable: false
    externals:
    - spec: libxt@system
      prefix: /usr
  xproto:
    version: [7.0.31]
    buildable: false
    externals:
    - spec: xproto@7.0.31
      prefix: /usr
  ncurses:
    version: [5.9]
    buildable: false
    externals:
    - spec: ncurses@5.9
      prefix: /usr
  perl:
    version: [5.16.3]
    buildable: false
    externals:
    - spec: perl@5.16.3
      prefix: /usr
  hwloc: 
    version: [5.7.5]
    buildable: false
    externals:
    - spec: hwloc@5.7.5
      prefix: /usr
  numactl: 
    version: [system]
    buildable: false
    externals:
    - spec: numactl@system
      prefix: /usr
#  llvm:
#    buildable: false
#    externals:
#    - spec: llvm@10.0.1+clang
#      prefix: /usr/tce/packages/clang/clang-10.0.1
#    - spec: llvm@11.0.0+clang
#      prefix: /usr/tce/packages/clang/clang-11.0.0
#  python:
#    version: [3.7.2]
#    buildable: false
#    externals:
#    - spec: python@3.7.2
#      prefix: /usr/tce/pacakges/python/python-3.7.2
